/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedCajaRouteImport } from './routes/_authenticated/caja'
import { Route as AuthenticatedCie10RouteImport } from './routes/_authenticated/cie10'
import { Route as AuthenticatedCirugiasRouteImport } from './routes/_authenticated/cirugias'
import { Route as AuthenticatedConfiguracionRouteImport } from './routes/_authenticated/configuracion'
import { Route as AuthenticatedConsultaRouteImport } from './routes/_authenticated/consulta'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated/documentos'
import { Route as AuthenticatedEstadisticasRouteImport } from './routes/_authenticated/estadisticas'
import { Route as AuthenticatedEstudiosComplementariosRouteImport } from './routes/_authenticated/estudios-complementarios'
import { Route as AuthenticatedFormatosRouteImport } from './routes/_authenticated/formatos'
import { Route as AuthenticatedHistoriasVaciasRouteImport } from './routes/_authenticated/historias-vacias'
import { Route as AuthenticatedImportarRouteImport } from './routes/_authenticated/importar'
import { Route as AuthenticatedInvestigacionRouteImport } from './routes/_authenticated/investigacion'
import { Route as AuthenticatedLaboratorioRouteImport } from './routes/_authenticated/laboratorio'
import { Route as AuthenticatedLinksObrasSocialesRouteImport } from './routes/_authenticated/links-obras-sociales'
import { Route as AuthenticatedMedicamentosRouteImport } from './routes/_authenticated/medicamentos'
import { Route as AuthenticatedPacientesRouteImport } from './routes/_authenticated/pacientes'
import { Route as AuthenticatedPanelRouteImport } from './routes/_authenticated/panel'
import { Route as AuthenticatedPlantillasRouteImport } from './routes/_authenticated/plantillas'
import { Route as AuthenticatedPracticasRouteImport } from './routes/_authenticated/practicas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCajaRoute = AuthenticatedCajaRouteImport.update({
  id: '/caja',
  path: '/caja',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCie10Route = AuthenticatedCie10RouteImport.update({
  id: '/cie10',
  path: '/cie10',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCirugiasRoute = AuthenticatedCirugiasRouteImport.update({
  id: '/cirugias',
  path: '/cirugias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracionRoute =
  AuthenticatedConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConsultaRoute = AuthenticatedConsultaRouteImport.update({
  id: '/consulta',
  path: '/consulta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstadisticasRoute =
  AuthenticatedEstadisticasRouteImport.update({
    id: '/estadisticas',
    path: '/estadisticas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstudiosComplementariosRoute =
  AuthenticatedEstudiosComplementariosRouteImport.update({
    id: '/estudios-complementarios',
    path: '/estudios-complementarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFormatosRoute = AuthenticatedFormatosRouteImport.update({
  id: '/formatos',
  path: '/formatos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoriasVaciasRoute =
  AuthenticatedHistoriasVaciasRouteImport.update({
    id: '/historias-vacias',
    path: '/historias-vacias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImportarRoute = AuthenticatedImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvestigacionRoute =
  AuthenticatedInvestigacionRouteImport.update({
    id: '/investigacion',
    path: '/investigacion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLaboratorioRoute =
  AuthenticatedLaboratorioRouteImport.update({
    id: '/laboratorio',
    path: '/laboratorio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLinksObrasSocialesRoute =
  AuthenticatedLinksObrasSocialesRouteImport.update({
    id: '/links-obras-sociales',
    path: '/links-obras-sociales',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMedicamentosRoute =
  AuthenticatedMedicamentosRouteImport.update({
    id: '/medicamentos',
    path: '/medicamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPacientesRoute = AuthenticatedPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPanelRoute = AuthenticatedPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlantillasRoute = AuthenticatedPlantillasRouteImport.update({
  id: '/plantillas',
  path: '/plantillas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPracticasRoute = AuthenticatedPracticasRouteImport.update({
  id: '/practicas',
  path: '/practicas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/caja': typeof AuthenticatedCajaRoute
  '/cie10': typeof AuthenticatedCie10Route
  '/cirugias': typeof AuthenticatedCirugiasRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/consulta': typeof AuthenticatedConsultaRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/estadisticas': typeof AuthenticatedEstadisticasRoute
  '/estudios-complementarios': typeof AuthenticatedEstudiosComplementariosRoute
  '/formatos': typeof AuthenticatedFormatosRoute
  '/historias-vacias': typeof AuthenticatedHistoriasVaciasRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/investigacion': typeof AuthenticatedInvestigacionRoute
  '/laboratorio': typeof AuthenticatedLaboratorioRoute
  '/links-obras-sociales': typeof AuthenticatedLinksObrasSocialesRoute
  '/medicamentos': typeof AuthenticatedMedicamentosRoute
  '/pacientes': typeof AuthenticatedPacientesRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/plantillas': typeof AuthenticatedPlantillasRoute
  '/practicas': typeof AuthenticatedPracticasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/caja': typeof AuthenticatedCajaRoute
  '/cie10': typeof AuthenticatedCie10Route
  '/cirugias': typeof AuthenticatedCirugiasRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/consulta': typeof AuthenticatedConsultaRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/estadisticas': typeof AuthenticatedEstadisticasRoute
  '/estudios-complementarios': typeof AuthenticatedEstudiosComplementariosRoute
  '/formatos': typeof AuthenticatedFormatosRoute
  '/historias-vacias': typeof AuthenticatedHistoriasVaciasRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/investigacion': typeof AuthenticatedInvestigacionRoute
  '/laboratorio': typeof AuthenticatedLaboratorioRoute
  '/links-obras-sociales': typeof AuthenticatedLinksObrasSocialesRoute
  '/medicamentos': typeof AuthenticatedMedicamentosRoute
  '/pacientes': typeof AuthenticatedPacientesRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/plantillas': typeof AuthenticatedPlantillasRoute
  '/practicas': typeof AuthenticatedPracticasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/caja': typeof AuthenticatedCajaRoute
  '/_authenticated/cie10': typeof AuthenticatedCie10Route
  '/_authenticated/cirugias': typeof AuthenticatedCirugiasRoute
  '/_authenticated/configuracion': typeof AuthenticatedConfiguracionRoute
  '/_authenticated/consulta': typeof AuthenticatedConsultaRoute
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRoute
  '/_authenticated/estadisticas': typeof AuthenticatedEstadisticasRoute
  '/_authenticated/estudios-complementarios': typeof AuthenticatedEstudiosComplementariosRoute
  '/_authenticated/formatos': typeof AuthenticatedFormatosRoute
  '/_authenticated/historias-vacias': typeof AuthenticatedHistoriasVaciasRoute
  '/_authenticated/importar': typeof AuthenticatedImportarRoute
  '/_authenticated/investigacion': typeof AuthenticatedInvestigacionRoute
  '/_authenticated/laboratorio': typeof AuthenticatedLaboratorioRoute
  '/_authenticated/links-obras-sociales': typeof AuthenticatedLinksObrasSocialesRoute
  '/_authenticated/medicamentos': typeof AuthenticatedMedicamentosRoute
  '/_authenticated/pacientes': typeof AuthenticatedPacientesRoute
  '/_authenticated/panel': typeof AuthenticatedPanelRoute
  '/_authenticated/plantillas': typeof AuthenticatedPlantillasRoute
  '/_authenticated/practicas': typeof AuthenticatedPracticasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agenda'
    | '/caja'
    | '/cie10'
    | '/cirugias'
    | '/configuracion'
    | '/consulta'
    | '/documentos'
    | '/estadisticas'
    | '/estudios-complementarios'
    | '/formatos'
    | '/historias-vacias'
    | '/importar'
    | '/investigacion'
    | '/laboratorio'
    | '/links-obras-sociales'
    | '/medicamentos'
    | '/pacientes'
    | '/panel'
    | '/plantillas'
    | '/practicas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agenda'
    | '/caja'
    | '/cie10'
    | '/cirugias'
    | '/configuracion'
    | '/consulta'
    | '/documentos'
    | '/estadisticas'
    | '/estudios-complementarios'
    | '/formatos'
    | '/historias-vacias'
    | '/importar'
    | '/investigacion'
    | '/laboratorio'
    | '/links-obras-sociales'
    | '/medicamentos'
    | '/pacientes'
    | '/panel'
    | '/plantillas'
    | '/practicas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agenda'
    | '/_authenticated/caja'
    | '/_authenticated/cie10'
    | '/_authenticated/cirugias'
    | '/_authenticated/configuracion'
    | '/_authenticated/consulta'
    | '/_authenticated/documentos'
    | '/_authenticated/estadisticas'
    | '/_authenticated/estudios-complementarios'
    | '/_authenticated/formatos'
    | '/_authenticated/historias-vacias'
    | '/_authenticated/importar'
    | '/_authenticated/investigacion'
    | '/_authenticated/laboratorio'
    | '/_authenticated/links-obras-sociales'
    | '/_authenticated/medicamentos'
    | '/_authenticated/pacientes'
    | '/_authenticated/panel'
    | '/_authenticated/plantillas'
    | '/_authenticated/practicas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caja': {
      id: '/_authenticated/caja'
      path: '/caja'
      fullPath: '/caja'
      preLoaderRoute: typeof AuthenticatedCajaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cie10': {
      id: '/_authenticated/cie10'
      path: '/cie10'
      fullPath: '/cie10'
      preLoaderRoute: typeof AuthenticatedCie10RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cirugias': {
      id: '/_authenticated/cirugias'
      path: '/cirugias'
      fullPath: '/cirugias'
      preLoaderRoute: typeof AuthenticatedCirugiasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracion': {
      id: '/_authenticated/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AuthenticatedConfiguracionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/consulta': {
      id: '/_authenticated/consulta'
      path: '/consulta'
      fullPath: '/consulta'
      preLoaderRoute: typeof AuthenticatedConsultaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estadisticas': {
      id: '/_authenticated/estadisticas'
      path: '/estadisticas'
      fullPath: '/estadisticas'
      preLoaderRoute: typeof AuthenticatedEstadisticasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estudios-complementarios': {
      id: '/_authenticated/estudios-complementarios'
      path: '/estudios-complementarios'
      fullPath: '/estudios-complementarios'
      preLoaderRoute: typeof AuthenticatedEstudiosComplementariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/formatos': {
      id: '/_authenticated/formatos'
      path: '/formatos'
      fullPath: '/formatos'
      preLoaderRoute: typeof AuthenticatedFormatosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historias-vacias': {
      id: '/_authenticated/historias-vacias'
      path: '/historias-vacias'
      fullPath: '/historias-vacias'
      preLoaderRoute: typeof AuthenticatedHistoriasVaciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/importar': {
      id: '/_authenticated/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof AuthenticatedImportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investigacion': {
      id: '/_authenticated/investigacion'
      path: '/investigacion'
      fullPath: '/investigacion'
      preLoaderRoute: typeof AuthenticatedInvestigacionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/laboratorio': {
      id: '/_authenticated/laboratorio'
      path: '/laboratorio'
      fullPath: '/laboratorio'
      preLoaderRoute: typeof AuthenticatedLaboratorioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/links-obras-sociales': {
      id: '/_authenticated/links-obras-sociales'
      path: '/links-obras-sociales'
      fullPath: '/links-obras-sociales'
      preLoaderRoute: typeof AuthenticatedLinksObrasSocialesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/medicamentos': {
      id: '/_authenticated/medicamentos'
      path: '/medicamentos'
      fullPath: '/medicamentos'
      preLoaderRoute: typeof AuthenticatedMedicamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pacientes': {
      id: '/_authenticated/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof AuthenticatedPacientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panel': {
      id: '/_authenticated/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AuthenticatedPanelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plantillas': {
      id: '/_authenticated/plantillas'
      path: '/plantillas'
      fullPath: '/plantillas'
      preLoaderRoute: typeof AuthenticatedPlantillasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practicas': {
      id: '/_authenticated/practicas'
      path: '/practicas'
      fullPath: '/practicas'
      preLoaderRoute: typeof AuthenticatedPracticasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedCajaRoute: typeof AuthenticatedCajaRoute
  AuthenticatedCie10Route: typeof AuthenticatedCie10Route
  AuthenticatedCirugiasRoute: typeof AuthenticatedCirugiasRoute
  AuthenticatedConfiguracionRoute: typeof AuthenticatedConfiguracionRoute
  AuthenticatedConsultaRoute: typeof AuthenticatedConsultaRoute
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRoute
  AuthenticatedEstadisticasRoute: typeof AuthenticatedEstadisticasRoute
  AuthenticatedEstudiosComplementariosRoute: typeof AuthenticatedEstudiosComplementariosRoute
  AuthenticatedFormatosRoute: typeof AuthenticatedFormatosRoute
  AuthenticatedHistoriasVaciasRoute: typeof AuthenticatedHistoriasVaciasRoute
  AuthenticatedImportarRoute: typeof AuthenticatedImportarRoute
  AuthenticatedInvestigacionRoute: typeof AuthenticatedInvestigacionRoute
  AuthenticatedLaboratorioRoute: typeof AuthenticatedLaboratorioRoute
  AuthenticatedLinksObrasSocialesRoute: typeof AuthenticatedLinksObrasSocialesRoute
  AuthenticatedMedicamentosRoute: typeof AuthenticatedMedicamentosRoute
  AuthenticatedPacientesRoute: typeof AuthenticatedPacientesRoute
  AuthenticatedPanelRoute: typeof AuthenticatedPanelRoute
  AuthenticatedPlantillasRoute: typeof AuthenticatedPlantillasRoute
  AuthenticatedPracticasRoute: typeof AuthenticatedPracticasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedCajaRoute: AuthenticatedCajaRoute,
  AuthenticatedCie10Route: AuthenticatedCie10Route,
  AuthenticatedCirugiasRoute: AuthenticatedCirugiasRoute,
  AuthenticatedConfiguracionRoute: AuthenticatedConfiguracionRoute,
  AuthenticatedConsultaRoute: AuthenticatedConsultaRoute,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRoute,
  AuthenticatedEstadisticasRoute: AuthenticatedEstadisticasRoute,
  AuthenticatedEstudiosComplementariosRoute:
    AuthenticatedEstudiosComplementariosRoute,
  AuthenticatedFormatosRoute: AuthenticatedFormatosRoute,
  AuthenticatedHistoriasVaciasRoute: AuthenticatedHistoriasVaciasRoute,
  AuthenticatedImportarRoute: AuthenticatedImportarRoute,
  AuthenticatedInvestigacionRoute: AuthenticatedInvestigacionRoute,
  AuthenticatedLaboratorioRoute: AuthenticatedLaboratorioRoute,
  AuthenticatedLinksObrasSocialesRoute: AuthenticatedLinksObrasSocialesRoute,
  AuthenticatedMedicamentosRoute: AuthenticatedMedicamentosRoute,
  AuthenticatedPacientesRoute: AuthenticatedPacientesRoute,
  AuthenticatedPanelRoute: AuthenticatedPanelRoute,
  AuthenticatedPlantillasRoute: AuthenticatedPlantillasRoute,
  AuthenticatedPracticasRoute: AuthenticatedPracticasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
