-- Catálogo de análisis de laboratorio (prefijo "Lab - ") para pedidos de estudios.
-- Migración idempotente: registra en el repositorio las 62 filas ya aplicadas en la base.
INSERT INTO public.practicas_estudios (obra_social, nombre, codigo, contenido, owner_id)
SELECT v.obra_social, v.nombre, v.codigo, v.contenido, u.id
FROM (VALUES
(NULL, 'Lab - Ac. anti Factor Intrínseco (F1)', '', 'Solicito Ac. anti Factor Intrínseco (F1) en el laboratorio.'),
(NULL, 'Lab - Ácido Fólico', '', 'Solicito Ácido Fólico en el laboratorio.'),
(NULL, 'Lab - Ácido Láctico', '', 'Solicito Ácido Láctico en el laboratorio.'),
(NULL, 'Lab - ACRA', '', 'Solicito ACRA en el laboratorio.'),
(NULL, 'Lab - Aldolasa', '', 'Solicito Aldolasa en el laboratorio.'),
(NULL, 'Lab - Amilasa', '', 'Solicito Amilasa en el laboratorio.'),
(NULL, 'Lab - ANCA (Y y C)', '', 'Solicito ANCA (Y y C) en el laboratorio.'),
(NULL, 'Lab - Anti Músculo liso (ASMA)', '', 'Solicito Anti Músculo liso (ASMA) en el laboratorio.'),
(NULL, 'Lab - anti Tiroglobulina (us)', '', 'Solicito anti Tiroglobulina (us) en el laboratorio.'),
(NULL, 'Lab - anti Transglutaminasa-IgA', '', 'Solicito anti Transglutaminasa-IgA en el laboratorio.'),
(NULL, 'Lab - Anticardiolipina IgG-IgM', '', 'Solicito Anticardiolipina IgG-IgM en el laboratorio.'),
(NULL, 'Lab - Anticoagulante lúpico', '', 'Solicito Anticoagulante lúpico en el laboratorio.'),
(NULL, 'Lab - ASTO', '', 'Solicito ASTO en el laboratorio.'),
(NULL, 'Lab - aTPO', '', 'Solicito aTPO en el laboratorio.'),
(NULL, 'Lab - B2 Glicoproteína', '', 'Solicito B2 Glicoproteína en el laboratorio.'),
(NULL, 'Lab - Calcemia', '', 'Solicito Calcemia en el laboratorio.'),
(NULL, 'Lab - Calciuria', '', 'Solicito Calciuria en el laboratorio.'),
(NULL, 'Lab - Chagas (Serología)', '', 'Solicito Chagas (Serología) en el laboratorio.'),
(NULL, 'Lab - Clearance de Creatinina', '', 'Solicito Clearance de Creatinina en el laboratorio.'),
(NULL, 'Lab - Coagulograma', '', 'Solicito Coagulograma en el laboratorio.'),
(NULL, 'Lab - Colesterol HDL', '', 'Solicito Colesterol HDL en el laboratorio.'),
(NULL, 'Lab - Colesterol LDL', '', 'Solicito Colesterol LDL en el laboratorio.'),
(NULL, 'Lab - Colesterol Total', '', 'Solicito Colesterol Total en el laboratorio.'),
(NULL, 'Lab - CPK', '', 'Solicito CPK en el laboratorio.'),
(NULL, 'Lab - Creatinina con IFGe', '', 'Solicito Creatinina con IFGe en el laboratorio.'),
(NULL, 'Lab - Creatininuria', '', 'Solicito Creatininuria en el laboratorio.'),
(NULL, 'Lab - ECA', '', 'Solicito ECA en el laboratorio.'),
(NULL, 'Lab - Factor Reumatoideo', '', 'Solicito Factor Reumatoideo en el laboratorio.'),
(NULL, 'Lab - FAN', '', 'Solicito FAN en el laboratorio.'),
(NULL, 'Lab - Ferremia', '', 'Solicito Ferremia en el laboratorio.'),
(NULL, 'Lab - FTA-Abs', '', 'Solicito FTA-Abs en el laboratorio.'),
(NULL, 'Lab - Glucemia', '', 'Solicito Glucemia en el laboratorio.'),
(NULL, 'Lab - HBA1C', '', 'Solicito HBA1C en el laboratorio.'),
(NULL, 'Lab - HBsAg', '', 'Solicito HBsAg en el laboratorio.'),
(NULL, 'Lab - HCV', '', 'Solicito HCV en el laboratorio.'),
(NULL, 'Lab - Hemograma Completo', '', 'Solicito Hemograma Completo en el laboratorio.'),
(NULL, 'Lab - Hepatograma', '', 'Solicito Hepatograma en el laboratorio.'),
(NULL, 'Lab - HIV', '', 'Solicito HIV en el laboratorio.'),
(NULL, 'Lab - HLA B27', '', 'Solicito HLA B27 en el laboratorio.'),
(NULL, 'Lab - HLA B29', '', 'Solicito HLA B29 en el laboratorio.'),
(NULL, 'Lab - HLA B51', '', 'Solicito HLA B51 en el laboratorio.'),
(NULL, 'Lab - IgA Total', '', 'Solicito IgA Total en el laboratorio.'),
(NULL, 'Lab - IgE Total', '', 'Solicito IgE Total en el laboratorio.'),
(NULL, 'Lab - Insulinemia', '', 'Solicito Insulinemia en el laboratorio.'),
(NULL, 'Lab - Ionograma', '', 'Solicito Ionograma en el laboratorio.'),
(NULL, 'Lab - Orina Completa', '', 'Solicito Orina Completa en el laboratorio.'),
(NULL, 'Lab - PCR', '', 'Solicito PCR en el laboratorio.'),
(NULL, 'Lab - Proteinuria 24hs', '', 'Solicito Proteinuria 24hs en el laboratorio.'),
(NULL, 'Lab - T4 libre', '', 'Solicito T4 libre en el laboratorio.'),
(NULL, 'Lab - Toxocara-IgG', '', 'Solicito Toxocara-IgG en el laboratorio.'),
(NULL, 'Lab - Toxocara-IgM', '', 'Solicito Toxocara-IgM en el laboratorio.'),
(NULL, 'Lab - Toxoplasmosis-IgG', '', 'Solicito Toxoplasmosis-IgG en el laboratorio.'),
(NULL, 'Lab - Toxoplasmosis-IgM', '', 'Solicito Toxoplasmosis-IgM en el laboratorio.'),
(NULL, 'Lab - TRABs II', '', 'Solicito TRABs II en el laboratorio.'),
(NULL, 'Lab - Triglicéridos', '', 'Solicito Triglicéridos en el laboratorio.'),
(NULL, 'Lab - TSH', '', 'Solicito TSH en el laboratorio.'),
(NULL, 'Lab - Uremia', '', 'Solicito Uremia en el laboratorio.'),
(NULL, 'Lab - Uricemia', '', 'Solicito Uricemia en el laboratorio.'),
(NULL, 'Lab - Urocultivo', '', 'Solicito Urocultivo en el laboratorio.'),
(NULL, 'Lab - VDRL', '', 'Solicito VDRL en el laboratorio.'),
(NULL, 'Lab - Vitamina B12', '', 'Solicito Vitamina B12 en el laboratorio.'),
(NULL, 'Lab - VSG', '', 'Solicito VSG en el laboratorio.')
) AS v(obra_social, nombre, codigo, contenido)
CROSS JOIN (SELECT id FROM auth.users WHERE email = 'marilischreiber@yahoo.com.ar' LIMIT 1) AS u(id)
WHERE NOT EXISTS (
  SELECT 1 FROM public.practicas_estudios p WHERE p.nombre = v.nombre
);
